version: '3'

services: 
  api: 
   restart: always
   build: .
   container_name: app
   ports:
   - "8080:8080"
   expose: 
   - "8080"
   depends_on: 
   - db
   
  db: 
   restart: always
   image: mysql:5.6
   container_name: db
   expose: 
   - "3306"
   ports:
   - "3308:3306"
   environment: 
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: todo_db
    MYSQL_USER: sa
    MYSQL_PASSWORD: password
    MYSQL_ROOT_HOST: '%'